require("plugins.pack")
require("plugins.theme")
require("plugins.editor")
require("plugins.treesitter")
require("plugins.formatting")
-- require("plugins.linting")
-- require("plugins.debug")
require("plugins.autocomplete")
require("plugins.snippets")
require("plugins.ui")
require("plugins.navegation")
require("plugins.lsp")
require("plugins.latex")
